# Activate with: quarto render --profile sim
project:
  # Render the manuscript plus the simulation pages
  type: book
  render:
    - index.qmd
    - R/stage_1_simulations/*.qmd

book:
  # keep the manuscript first, then add one chapter that *contains* all sims
  chapters:
    - part: "Data Descriptor Manuscript"
    - index.qmd
    - part: "Stage 1 Simulations"
      chapters:
        - R/stage_1_simulations/0_generateSyntheticData.qmd
        - R/stage_1_simulations/1_preprocess.qmd
        - R/stage_1_simulations/2_basicNeeds.qmd
        - R/stage_1_simulations/3_sleep.qmd
        - R/stage_1_simulations/4_genres.qmd