project:
  type: website
  execute-dir: project
  # Use Actions artifact, not docs/:
  output-dir: _site
  render:
    - data-process.qmd
    - index.qmd

execute:
  freeze: true

repo-url: https://github.com/digital-wellbeing/platform-study-rr
site-url: https://digital-wellbeing.github.io/platform-study-rr/
data-url: https://example.com
data-license: CC0