project:
  type: website
  execute-dir: project
  output-dir: _site
  render:
    - data-process.qmd
    - index.qmd

execute:
  freeze: auto

repo-url: https://github.com/digital-wellbeing/open-play
site-url: https://digital-wellbeing.github.io/open-play
data-url: https://example.com
data-license: CC0 (with supplemental reidentification clause)